### ISSUE TITLE
NuWeather: show wind speed in m/s

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [jlu5/SupyPlugins#97]
Opening this due to an IRC discussion, in other user name, so things don't get lost

### IRC snippet
#
\<malice> jlu5: The weather plugin returns wind speed in kph and mph, but here, normally meters per second is used instead
\<+jlu5> malice, can you open an issue?
\<malice> jlu5: I can not
\<+jlu5> wat
\<+jlu5> why
\<malice> No github
\<+jlu5> it's free ;)
\<malice> Yes
\<+jlu5> I'm pretty busy until the end of month so that's pretty much the only way to make sure your requests don't get lost..
\<malice> :(
#

Cheers

**Comment by jlu5** [comment]
Just for context, what parts of the world actually use m/s instead of km/h? Here in Canada we follow the metric system and km/h is standard on all the weather sites I see.

This is slightly annoying to code in because it probably doesn't make sense to show the same value in 3 units at once. We'd probably need the unit output to be configurable like it is for temperatures.

**Comment by PeGaSuS-Coder** [comment]
Quick Google search lead me to this [article](https://en.wikipedia.org/wiki/Wind_speed).

Small extract:
Meters per second (m/s) is the SI unit for velocity and the unit recommended by the World Meteorological Organization for reporting wind speeds, and is amongst others used in weather forecasts in the Nordic countries.

**Comment by Alcheri** [comment]
@jlu5

The standards in metric and imperial  are as follows:

Metres per second and feet per second.

Displaying these at Km/H or Mi/H gives the false impression that there are potential weather alerts in place for damaging winds.
